name: Build and Push POS Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'POS/backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: POS/backend
          push: true
          tags: |
            tastyfreshpos/tastyfreshpos:latest
            tastyfreshpos/tastyfreshpos:${{ github.sha }}
          cache-from: type=registry,ref=tastyfreshpos/tastyfreshpos:latest
          cache-to: type=registry,ref=tastyfreshpos/tastyfreshpos:latest,mode=max